### ISSUE TITLE
Compatibility with IntelliJ IDEA 2024.1

### ISSUE THREAD

**Issue by julien-carsique-sonarsource** [cirruslabs/intellij-starlark#9]
Hello,

After upgrading to IntelliJ IDEA 2024.1 (Community Edition), the plugin must be deactivated else the IDE will crash:
```
java.lang.Throwable: Forbidden to mutate SDK outside of the `SdkModificator`. Please, use `com.intellij.openapi.projectRoots.Sdk.getSdkModificator`
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.openapi.projectRoots.impl.ProjectJdkImpl.addRoot(ProjectJdkImpl.java:261)
	at org.cirruslabs.intellij.starlark.sdk.StarlarkSdk.<init>(StarlarkSdk.kt:16)
	at org.cirruslabs.intellij.starlark.facet.StarlarkFacetType$StarlarkFacetConfiguration.<init>(StarlarkFacetType.kt:47)
	at org.cirruslabs.intellij.starlark.facet.StarlarkFacetType.createDefaultConfiguration(StarlarkFacetType.kt:27)
	at org.cirruslabs.intellij.starlark.facet.StarlarkFacetType.createDefaultConfiguration(StarlarkFacetType.kt:16)
	at com.intellij.workspaceModel.ide.impl.legacyBridge.facet.FacetManagerBridge$Companion.createFacetFromStateRaw$intellij_platform_lang_impl(FacetManagerBridge.kt:90)
	...
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

IntelliJ IDEA 2024.1 (Community Edition)
Build #IC-241.14494.240, built on March 28, 2024

**Comment by fewstera** [comment]
I"m seeing a different critical error to @julien-carsique-sonarsource on `GoLand 2024.1 - Build #GO-241.14494.238, built on March 28, 2024`

```
Internal error. Please refer to https://jb.gg/ide/critical-startup-errors
java.lang.ExceptionInInitializerError
at org.cirruslabs.intellij.starlark.StarlarkFileType.<init> (StarlarkFileType.kt:7)
at org.cirruslabs.intellij.starlark.StarlarkFileType.<clinit>(StarlarkFileType.kt:9)
at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42)
at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:185)
at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1132)
at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1113)
at java.base/java.lang.reflect.Field.get(Field.java:425)
at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiateFileTypeBean(FileTypeManagerImpl.java:540)
at com.intellij.openapi.fileTypes.impl.FileTypeManagerlmpl.mergeOrInstantiateFileTypeBean(FileTypeManagerlmpl.java:482)
at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiatePendingFileTypes(FileTypeManagerImpl.java:475)
at com.intellij.openapi.fileTypes.impl.FileTypeManagerlmpl.initializeComponent(FileTypeManagerImpl.java:647)
at com.intellij.configurationStore.ComponentStorelmpl.initComponent(ComponentStorelmpl.kt:168)
at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:44)
at com.intellij.serviceContainer.ComponentManagerImpl.initializeServiceSintellij_platform_serviceContainer(ComponentManagerlmpl.kt:659)
at com.intellij.serviceContainer.Servicelnstancelnitializer.createlnstance$suspendImpl(Servicelnstancelnitializer.kt:70)
at com.intellij.serviceContainer.Servicelnstancelnitializer.createlnstance(Servicelnstancelnitializer.kt)
at com.intellij.platform.instanceContainer.internal.LazyInstanceHolderSinitialize$1$1.invokeSuspend(LazyInstanceHolder.kt:162)
at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt) at com.intellij.platform.instanceContainer.internal.LazyInstanceHolderSinitialize$1$1.invoke(LazyInstanceHolder.kt)
at kotinc.coroutines.Bullersk_Buiders.commonk.wthontexifulders.common.ke161)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
at com.intellij.platform.instanceContainer.internal.LazyInstanceHolderSinitialize$1.invokeSuspend(LazyInstanceHolder.kt:160)
at com.intellij.platform.instanceContainer.internal.LazyInstanceHolderSinitialize$1.invoke(LazyInstanceHolder.kt) at com.intellij.platform.instanceContainer.internal.LazyInstanceHolderSinitialize$1.invoke(LazyInstanceHolder.kt)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.initialize(LazyInstanceHolder.kt:145)
at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.accessSinitialize(LazyInstanceHolder.kt:13) at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.tryInitialize(LazyInstanceHolder.kt:135) at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt:95)
at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstanceSsuspendImpl(LazyInstanceHolder.kt:83)
at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt)
at com.intellij.platform.instanceContainer.internal.InstanceContainerlmpl.instance(InstanceContainerlmpl.kt:68)
at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsync(ComponentManagerImpl.kt:702)
at com.intellj-platform.ide.bootstrap.AppServicePreloadingKtSpostAppRegisteredS1SfileTypeManagerJobS1.invokeSuspend(appServicePreloading.kt:180)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793) at kolin.coroutinescheduling. CoroutineschedulerWorkerrunWorthostineer-edulerkt:697)
Caused by: com.intellij.diagnostic.PluginException: Class com.jetbrains.python.PythonLanguage must not be requested from main classloader of PythonCore plugin. Matches content module (packagePrefix=com.jetbrains.python., moduleName=intellij.python.community.impl). [Plugin: org.cirruslabs.intellij.plugins.starlark]
at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.kt:203)
at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:151)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
at org.cirruslabs.intellij.starlark.StarlarkLanguage.<init>(StarlarkLanguage.kt:6)
at org.cirruslabs.intellij.starlark.StarlarkLanguage. <clinit>(StarlarkLanguage.kt:8)
... 47 more


Your JRE: 17.0.10+8-b1207.12 aarch64 (JetBrains s.r.o.)
/Applications /GoLand.app/Contents/ibr/Contents/Home
```
